version: '3'

services:
    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        volumes:
            - /Users/sangyoon/Desktop/jen/:/var/jenkins_home
        ports:
            - "8080:8080"