spring:
  profiles:
    active: admin
    include: domain
  h2:
    console:
      enabled: true
  thymeleaf:
    cache: false
    check-template-location: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8082

