server:
  port: 8082
spring:
  h2:
    console:
      enabled: true
  thymeleaf:
    cache: false
    check-template-location: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  profiles:
    active: local
    include: core
  sql:
    init:
      mode: always
---
spring:
  sql:
    init:
      mode: always
  profiles:
    active: prod
    include: core
upload:
  image:
    player: /Users/shinhee/Desktop/images/
