spring:
#  profiles:
#    default: local
  #  datasource:
  #    url: jdbc:h2:mem:~/onTheLookApplication
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password:
    datasource:
      url: jdbc:h2:mem:~/kickOffApplication
      driver-class-name: org.h2.Driver
      username: sa
      password: