spring:
  profiles:
    active: local
    include: core
  batch:
    jdbc:
      initialize-schema: always
    job:
      name: dailyStandingInfoJob
server:
  port: 8083
api:
  footbool:
    token: b1a0c6ed997843cdbc8d22f33523bde6
#springdoc:
#  swagger-ui:
#    enabled: false
logging:
  level:
    root: info
    org:
      apache.catalina: info
#  file:
#    path: /var/libs/batch/logs
#    name: batch.log
