springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
    enabled: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**

jwt:
  secret-key: 56ab0682dda585b2997d3871c0921fb6929ef195501ab98b18c6870bdc808970fb041463f6792ae02a4c7458bc3e375095a03508f3bb2925eddf618a56d41540
---
spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/kick_off?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
logging:
  level:
    root: info
  file:
    path: ./logs
    name: local.log
server:
  tomcat:
    basedir: ./logs
    accesslog:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: prod
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:~/KickOffApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

server:
  tomcat:
    basedir: /home/ubuntu/logs/tomcat
    accesslog:
      enabled: true

logging:
  level:
    root: info
    org:
      apache.catalina: INFO
  file:
    path: /home/ubuntu/logs
    name: prod.log
