INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('QCAF','WC Qualification CAF','Africa','아프리카 축구 예선');
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('ASL','Liga Profesional','Argentina',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('QAFC','WC Qualification AFC','Asia', '아시아 축구 예선');
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('AAL','A League','Australia',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('APL','Playoffs 1/2','Austria',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('ABL','Bundesliga','Austria', '분데스리가');
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('BJPP','Playoffs','Belgium',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('BJL','Jupiler Pro League','Belgium',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('BSB','Campeonato Brasileiro Série B','Brazil',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('BSA','Campeonato Brasileiro Série A','Brazil',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('CPD','Primera División','Chile',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('CSL','Chinese Super League','China PR',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('CLP','Liga Postobón','Colombia',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('PRVA','Prva Liga','Croatia',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('DELP','Euro League - Playoff','Denmark',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('DSU','Superliga','Denmark',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('ELC','Championship','England',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('PL','Premier League','England',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('FLC','Football League Cup','England',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('EL1','League One','England',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('EL2','League Two','England',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('FAC','FA Cup','England',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('COM','FA Community Shield','England',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('EC','European Championship','Europe',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('EL','UEFA Europa League','Europe',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('UCL','UEFA Conference League','Europe',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('CL','UEFA Champions League','Europe',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('ESC','Supercup','Europe',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('QUFA','WC Qualification UEFA','Europe',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('VEI','Veikkausliiga','Finland',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('FL2','Ligue 2','France',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('FPL','Playoffs 1/2','France',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('FL1','Ligue 1','France',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('REG','Regionalliga','Germany',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('GSC','DFL Super Cup','Germany',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('BL3','3. Bundesliga','Germany',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('BLREL','Relegation','Germany',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('BL1','Bundesliga','Germany',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('BL2','2. Bundesliga','Germany',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('DFB','DFB-Pokal','Germany',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('GSL','Super League','Greece',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('HNB','NB I','Hungary',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('ILH','Ligat ha’Al','Israel',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('SA','Serie A','Italy',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('SB','Serie B','Italy',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('CIT','Coppa Italia','Italy',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('ISC','Serie C','Italy',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('IPL','Playoffs 1/2','Italy',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('JJL','J. League','Japan',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('LMX','Liga MX','Mexico',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('KNV','KNVB Beker','Netherlands',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('DED','Eredivisie','Netherlands',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('DJL','Eerste Divisie','Netherlands',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('TIP','Tippeligaen','Norway',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('QOFC','WC Qualification OFC','Oceania',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('PPD','Primera División','Peru',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('PPL','Primeira Liga','Portugal',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('RL1','Liga I','Romania',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('RFPL','RFPL','Russia',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('SPL','Premier League','Scotland',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('CLI','Copa Libertadores','South America',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('CA','Copa America','South America',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('QCBL','WC Qualification CONMEBOL','South America',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('SD','Segunda División','Spain',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('CDR','Copa del Rey','Spain',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('PD','Primera Division','Spain',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('ALL','Allsvenskan','Sweden',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('SSL','Super League','Switzerland',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('TSL','Süper Lig','Turkey',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('UPL','Premier Liha','United States',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('SUCU','Supercopa Uruguaya','Uruguay',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('OLY','Summer Olympics','World',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('WC','FIFA World Cup','World',null);
INSERT INTO league_code (league_code, caption, country, league_code_name) VALUES ('QCCF','WC Qualification CONCACAF','World',null);